repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-ast
    -   id: debug-statements

-   repo: https://github.com/PyCQA/flake8.git
    rev: 3.7.9
    hooks:
    - id: flake8
      args: ['--max-line-length', '88', '--exclude', '.git,__pycache__,.venv,venv']

repos:
  # Using this mirror lets us use mypyc-compiled black, which is about 2x faster
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.12.1
    hooks:
      - id: black
        
